config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  post '/search', to: 'home#search', as: 'search'

  resources :articles
  resources :analytics, only: %i[index]
end

app/models/analytic.rb
class Analytic < ApplicationRecord
  include AnalyticSearchable

  class << self
    def record(keyword)
      analytic = AnalyticSearch.new(:find_analytic, { keyword: keyword }).execute
      analytic = Analytic.create(keyword: keyword) if analytic.blank?
      analytic.increment!(:count)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include ArticleSearchable

  after_commit on: [:create] do
    __elasticsearch__.index_document
  end

  after_commit on: [:update] do
    __elasticsearch__.update_document
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document
  end

  extend FriendlyId
  friendly_id :title, use: :slugged

  enum state: { published: 0, unpublished: 1 }

  validates :title, :description, :state, presence: true
  validates_length_of :description, minimum: 5, maximum: 50

  class << self
    def match_by_keyword(keyword)
      Analytic.record(keyword)
      ArticleSearch.new(:find_articles, { keyword: keyword }).execute
    end
  end
end

app/models/concerns/analytic_searchable.rb
module AnalyticSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings index: {
      number_of_shards: 1,
      analysis: {
        analyzer: {
          full_text_matching: { tokenizer: :keyword }
        }
      }
    } do
      mappings dynamic: false do
        indexes :id,      type: :integer
        indexes :count,   type: :integer
        indexes :keyword, type: :text, analyzer: :keyword
      end
    end

    def as_indexed_json(options = nil)
      self.as_json( only: %i[id count keyword] )
    end
  end
end

app/models/concerns/article_searchable.rb
module ArticleSearchable
  extend ActiveSupport::Concern

  included do
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    settings index: {
      number_of_shards: 1,
      analysis: {
        analyzer: {
          title_matching: {
            type: :custom,
            tokenizer: :standard,
            filter: [ :lowercase, :asciifolding ]
          }
        }
      }
    } do
      mappings dynamic: false do
        indexes :id,    type: :integer
        indexes :title, type: :text, analyzer: :title_matching
      end
    end

    def as_indexed_json(options = nil)
      self.as_json( only: %i[id title state] )
    end
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    @analytics = AnalyticSearch.new(:all_analytics, {}).execute
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :load_article, only: %i[edit update show destroy]

  def index
    @articles = ArticleSearch.new(:all_articles, {}).execute
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path, notice: 'Article has been created successfully!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to articles_path, notice: 'Article has been updated successfully!'
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @article.destroy
      flash[:notice] = 'Article has been deleted successfully!'
    else
      flash[:alert] = 'Error! unable to delete article at the moment!'
    end

    redirect_to articles_path
  end

  private

  def load_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :state)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def search
    articles = Article.match_by_keyword(params[:keyword])
    render json: { articles: articles.pluck(:id, :title) }
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_flash_key(key)
    key == 'alert' ? 'danger' : 'success'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def nav_active_class(controller)
    params[:controller] == controller ? 'active' : ''
  end
end

app/views/analytics/index.html.erb
<div class="clearfix">
  <div class="float-left">
    <h3>Analytics</h3>
  </div>
</div>

<% if @analytics.present? %>
  <div class="table-responsive">  
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Keyword</th>
          <th scope="col">Search Count</th>
        </tr>
      </thead>
      <tbody>
        <% @analytics.each.with_index(1) do |analytic, index| %>
          <tr>
            <%= render 'analytics/partials/listing', analytic: analytic, index: index %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div>
    No Analytics Found!
  </div>
<% end %>

app/views/analytics/partials/_listing.html.erb
<th scope="row"><%= index %></th>
<td><%= analytic.keyword %></td>
<td><%= analytic.count %></td>

app/views/articles/edit.html.erb
<div class="clearfix">
  <div class="float-left">
    <h3>Edit Article</h3>
  </div>
  <div class="float-right">
    <%= link_to 'Back', articles_path, class: 'btn btn-success' %>
  </div>
</div>

<div>
  <%= render 'articles/partials/form' %>
</div>

app/views/articles/index.html.erb
<div class="clearfix">
  <div class="float-left">
    <h3>Articles</h3>
  </div>
  <div class="float-right">
    <%= link_to 'New Article', new_article_path, class: 'btn btn-success' %>
  </div>
</div>

<% if @articles.present? %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">State</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each.with_index(1) do |article, index| %>
          <tr>
            <%= render 'articles/partials/listing', article: article, index: index %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div>
    No Articles Found!
  </div>
<% end %>

app/views/articles/new.html.erb
<div class="clearfix">
  <div class="float-left">
    <h3>New Article</h3>
  </div>
  <div class="float-right">
    <%= link_to 'Back', articles_path, class: 'btn btn-success' %>
  </div>
</div>

<div>
  <%= render 'articles/partials/form' %>
</div>

app/views/articles/partials/_form.html.erb
<%= form_for @article, html: { 'data-parsley-validate': '' } do |f| %>
  <%= render 'partials/forms/errors', instance: @article %>

  <div class="form-group">
    <%= f.label :title, 'Title' %>
    <%= f.text_field :title, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :state, 'State' %>
    <%= f.select :state, options_for_select(Article.states.map { |k, v| [k.humanize, k] }, @article&.state), { include_blank: 'Please select a state' }, class: 'form-control', required: true %>
  </div>

  <div class="btn-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/partials/_listing.html.erb
<th scope="row"><%= index %></th>
<td><%= article.title %></td>
<td><%= article.description.truncate(20) %></td>
<td><%= article.state %></td>
<td>
  <%= link_to 'Show', article_path(article), class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Delete', article_path(article), method: :delete, class: 'btn btn-primary btn-sm', data: { confirm: 'Are you sure?' } %>
</td>

app/views/articles/show.html.erb
<div class="clearfix">
  <div class="float-left">
    <h3>Article</h3>
  </div>
  <div class="float-right">
    <%= link_to 'Back', articles_path, class: 'btn btn-success' %>
  </div>
</div>

<div class="table-responsive">  
  <table class="table">
    <body>
      <tr>
        <th scope="col">Title</th>
        <td><%= @article.title %></td>
      </tr>
      <tr>
        <th scope="col">Description</th>
        <td><%= @article.description.truncate(20) %></td>
      </tr>
      <tr>
        <th scope="col">State</th>
        <td><%= @article.state.humanize %></td>
      </tr>
    </body>
  </table>
</div>

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Articles</h1>
    <p class="lead">Search Articles</p>
  </div>
</div>

<div id="main-search-form">
  <%= form_tag search_path, remote: true, class: 'form-horizontal' do %>
    <div class="row text-center">
      <div class="col-sm-12">
        <div class="form-group">
          <%= text_field_tag :search, nil, placeholder: 'Search for articles...', class: 'form-control', id: 'search_keyword' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/search.js.erb
// $('#search_keyword').autocomplete({
//   _renderItem: function(ul, item) {
//     return $('<li>')
//       .attr('data-value', item.value)
//       .append(item.label)
//       .appendTo(ul);
//   }
// });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport" />

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render 'partials/public/header' %>

    <div id="start-main-content" class="container">
      <%= render 'partials/public/flash' %>
      <div class="row">
        <div class="col-sm-12">
          <div class="bg-light p-3 rounded border-dark-gray">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <%= render 'partials/public/footer' %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/partials/forms/_errors.html.erb
<% if instance.errors.present? %>
  <div class="alert errors alert-danger" role="alert">
    <ul>
      <% instance.errors.full_messages.each do |error_message| %>
        <li>
          <%= error_message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>